services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/datafortress
      SPRING_DATASOURCE_USERNAME: biba
      SPRING_DATASOURCE_PASSWORD: boba
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: biba
      POSTGRES_PASSWORD: boba
      POSTGRES_DB: datafortress
    ports:
      - "5433:5432"
